### ISSUE TITLE
ModuleNotFoundError: No module named 'parallel_model'

### ISSUE THREAD

**Issue by misiektw** [Kamlesh364/Mask-RCNN-TF2.7.0-keras2.7.0#13]
It is the issue from https://github.com/Kamlesh364/Mask-RCNN-TF2.7.0-keras2.7.0/issues/6 but its not connected to multiple GPUs, so I'm opening separate issue for someone looking after solution.

Assuming "import mcrnn" works, but you're getting "ModuleNotFoundError: No module named 'parallel_model' then change line 27 in https://github.com/Kamlesh364/Mask-RCNN-TF2.7.0-keras2.7.0/blob/main/mrcnn/model.py:
```
from parallel_model import ParallelModel
```
to:
```
from mrcnn.parallel_model import ParallelModel
```
No need to adding extra sys.path then to mrcnn directory then.

**Comment by Kamlesh364** [comment]
> It is the issue from #6 but its not connected to multiple GPUs, so I'm opening separate issue for someone looking after solution.
> 
> Assuming "import mcrnn" works, but you're getting "ModuleNotFoundError: No module named 'parallel_model' then change line 27 in https://github.com/Kamlesh364/Mask-RCNN-TF2.7.0-keras2.7.0/blob/main/mrcnn/model.py:
> 
> ```
> from parallel_model import ParallelModel
> ```
> 
> to:
> 
> ```
> from mrcnn.parallel_model import ParallelModel
> ```
> 
> No need to adding extra sys.path then to mrcnn directory then.

@misiektw Thankyou for your reply to the issue, but it can't be generalized because of the issues with root user. The solution to the problems differs based in the system user definition.

**Comment by misiektw** [comment]
> @misiektw Thankyou for your reply to the issue, but it can't be generalized because of the issues with root user. The solution to the problems differs based in the system user definition.

Not sure why one would run this as root, however even then this would resolve both cases, no?:
```
try:
    from parallel_model import ParallelModel
except ModuleNotFoundError:
    from mrcnn.parallel_model import ParallelModel
```

**Comment by Kamlesh364** [comment]
> 
Sorry to say but it won't work for everyone, and I'm suggesting this based on lot of experimentation.
