### ISSUE TITLE
Unable to use multiple GPU (No module named 'parallel_model')

### ISSUE THREAD

**Issue by ErinYang96** [Kamlesh364/Mask-RCNN-TF2.7.0-keras2.7.0#6]
Hi,

I am trying to work with two GPUs on our lab server. So I revise the `GPU_COUNT = 2` in the class Config(Config) and the class InferenceConfig. Everything else remains the same as the setup when I use only one GPU, which by the way, works fine. 
However, with two GPU, the error `No module named 'parallel_model` occurred. I have checked the source code, and found that `parallel_model.py` is definitely installed together with `model.py` in mrcnn packages. But it just cannot be found and worked.
Could you help me check what's wrong with this problem? Thanks for your kind support.

Best,
Fan

**Comment by Kamlesh364** [comment]
@ErinYang96 
Please add this line, above the line `from parallel_model import ParallelModel` -
`sys.path.append(mrcnn_dir)`
put full path of `mrcnn` folder, in which `parallel_model.py` and other scripts are placed.

best regards,
Kamlesh

**Comment by Kamlesh364** [comment]
please reopen, if you could not find the solution.

**Comment by ErinYang96** [comment]
@Kamlesh364 
I can load the `parallel_model` successfully following your instruction.  I also make changes on line 135 of `parallel_model.py` to prevent the error `AttributeError: module 'tensorflow' has no attribute 'reset_default_graph'` by using `tf.compat.v1.reset_default_graph()` instead. However, after making these changes, other errors also emerge (see below).
```
Traceback (most recent call last):
  File "C:\Apps\Anaconda3\envs\FishSeg\lib\site-packages\keras\engine\training.py", line 303, in __setattr__
    self._base_model_initialized
  File "parallel_model.py", line 48, in __getattribute__
    return super(ParallelModel, self).__getattribute__(attrname)
AttributeError: 'ParallelModel' object has no attribute '_base_model_initialized'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "parallel_model.py", line 163, in <module>
    model = ParallelModel(model, GPU_COUNT)
  File "parallel_model.py", line 36, in __init__
    self.inner_model = keras_model
  File "C:\Apps\Anaconda3\envs\FishSeg\lib\site-packages\keras\engine\training.py", line 305, in __setattr__
    raise RuntimeError(
RuntimeError: It looks like you are subclassing `Model` and you forgot to call `super().__init__()`. Always start with this line.
```
In `parallel_model.py`, I can see that the mentioned `super().__init__()` is included in the `class ParallelModel of def __init__()` as follow.
```
def __init__(self, keras_model, gpu_count):
    """Class constructor.
    keras_model: The Keras model to parallelize
    gpu_count: Number of GPUs. Must be > 1
    """
    
    self.inner_model = keras_model
    self.gpu_count = gpu_count
    merged_outputs = self.make_parallel()
    super(ParallelModel, self).__init__(inputs=self.inner_model.inputs,
                                        outputs=merged_outputs)
```
Could you check for me where the problem is? Thanks for your kindness.

**Comment by ErinYang96** [comment]
> please reopen, if you could not find the solution.

I am not allowed to re-open the issue. If you find this is an interesting problem, please re-open it. Thanks.

**Comment by ErinYang96** [comment]
It seems that I have found the possible solutions.

1. Downgrade keras version to 2.1.3 (see [here](https://github.com/matterport/Mask_RCNN/issues/1601));
2. Revise the `parallel_model.py` following PR [#1261](https://github.com/matterport/Mask_RCNN/pull/1261/commits/cf5541fe1382ee546934ee6206eec37d43b14542) and [#1241](https://github.com/matterport/Mask_RCNN/pull/1241).

I will try to solve the problem from solution2. And I will let you know if it works.

**Comment by ErinYang96** [comment]
@Kamlesh364 
Well, none of the PR work for me (tensorflow 2.7.0, keras 2.7.0). However, I still post my error messages as below, in case they may help you solve the problem.

**For PR 1241**
```
Traceback (most recent call last):
  File "parallel_model_1241.py", line 176, in <module>
    model = ParallelModel(model, GPU_COUNT)
  File "parallel_model_1241.py", line 42, in __init__
    merged_outputs = self.make_parallel(inner_model)
  File "parallel_model_1241.py", line 71, in make_parallel
    for name, x in zip(inner_model.input_names,
TypeError: 'NoneType' object is not iterable
```
**For PR 1261**
```
Traceback (most recent call last):
  File "parallel_model.py", line 181, in <module>
    model = ParallelModel(model, GPU_COUNT)
  File "parallel_model.py", line 36, in __init__
    merged_outputs = self.make_parallel(keras_model,gpu_count)
  File "parallel_model.py", line 90, in make_parallel
    inputs = [
  File "parallel_model.py", line 91, in <listcomp>
    KL.Lambda(lambda s: input_slices[name][i],
  File "C:\Apps\Anaconda3\envs\FishSeg\lib\site-packages\keras\utils\traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Apps\Anaconda3\envs\FishSeg\lib\site-packages\tensorflow\python\framework\type_spec.py", line 867, in type_spec_from_value
    raise TypeError(f"Could not build a TypeSpec for {value} of "
TypeError: Could not build a TypeSpec for KerasTensor(type_spec=TensorSpec(shape=(None, 28, 28, 1), dtype=tf.float32, name=None), name='tf.split/split:0', description="created by layer 'tf.split'") of unsupported type <class 'keras.engine.keras_tensor.KerasTensor'>.
```
Except for the two PR, I also test another version of `parallel_model.py`, which is claimed to be suitable for keras 2.4.0 (check [here](https://gist.github.com/skywalkerisnull/cebc1fc2b00fa76da92173d2baa21714)). The error message is the same as the current parallel_model.py version.
It seems to be related to keras version, but I want to stick to the current keras 2.7.0 in case some other errors occur. Could you take time to see how to revise the `parallel_model.py` to make it suitable for this set of Mask_RCNN? Thanks for your patience and great works!

Best,
Erin

**Comment by Kamlesh364** [comment]
@ErinYang96 
Please do not downgrade the keras version, it may cause unsolvable conflicts with the main `mrcnn.py` model script.

As mentioned in the [repository](https://github.com/kamlesh364/Mask-RCNN-TF2.7.0-keras2.7.0) description. My implementation of MRCNN is an edit to the original [MRCNN](https://github.com/matterport/Mask_RCNN). And, unfortunately I have not edited the `parallel_model.py` file, so it is same as the original MRCNN by [matterport](https://github.com/matterport/).

I would encourage you to debug all the errors with keras==2.7.0, only. This would require sufficient efforts to solve the errors one-by-one. This is the only solution to use multiple GPU with current implementation.

I would suggest you to read the official documentations of Tensorflow and Keras, to solve these errors. This would also enhance your skills in this field and make a significant contribution to [this](https://github.com/kamlesh364/Mask-RCNN-TF2.7.0-keras2.7.0) project.

I am also spending time in this direction, but it will take time for me to do this because I am currently engaged with other projects related to Deep Learning, as well. So, I would recommend you to edit `parallel_model.py` for keras2.7.0 and tf2.7.0.

If you could do that, I'll surely give you credit to this project officially, and make you a contributor to this project.

best of luck,
Kamlesh

**Comment by ErinYang96** [comment]
@Kamlesh364 Hi, it seems that I have solved this problem.
I try many methods, and finally I add only one line in `class ParallelModel()` to make it work, see below:
```
def __init__(self, keras_model, gpu_count):
    """Class constructor.
    keras_model: The Keras model to parallelize
    gpu_count: Number of GPUs. Must be > 1
    """
    
    super(ParallelModel, self).__init__() # this is the only line that I add
    self.inner_model = keras_model
    self.gpu_count = gpu_count        
    merged_outputs = self.make_parallel()
    super(ParallelModel, self).__init__(inputs=self.inner_model.inputs,
                                outputs=merged_outputs)
```
After this simple revision, my training process can use two GPUs. However, after finishing the training for head layer and fine tuning all layers, an extra error is reported as below:
```
Traceback (most recent call last):

  File "C:\Mask_RCNN_FishSeg\trout\FishSeg_server_test.py", line 276, in <module>
    model = modellib.MaskRCNN(mode="inference",

  File "C:\Apps\Anaconda3\envs\FishSeg\lib\site-packages\mrcnn\model.py", line 1844, in __init__
    self.keras_model = self.build(mode=mode, config=config)

  File "C:\Apps\Anaconda3\envs\FishSeg\lib\site-packages\mrcnn\model.py", line 2077, in build
    model = ParallelModel(model, config.GPU_COUNT)

  File "C:\Apps\Anaconda3\envs\FishSeg\Lib\site-packages\mrcnn\parallel_model.py", line 36, in __init__
    super(ParallelModel, self).__init__()

  File "C:\Apps\Anaconda3\envs\FishSeg\lib\site-packages\tensorflow\python\training\tracking\base.py", line 530, in _method_wrapper
    result = method(self, *args, **kwargs)

TypeError: __init__() missing 2 required positional arguments: 'inputs' and 'outputs'
```
The error seems to be a result of an extra GPU with no inputs or outputs. Maybe you can further check why this happens.

Best,
Erin

**Comment by Kamlesh364** [comment]
Your definition of `super()` function seems wrong to me, please look into the [documentations ](https://www.w3schools.com/python/ref_func_super.asp)of its uses, I am pretty sure you'll find the solution, immediately.

**Comment by Kamlesh364** [comment]
> @Kamlesh364 Well, none of the PR work for me (tensorflow 2.7.0, keras 2.7.0). However, I still post my error messages as below, in case they may help you solve the problem.
> 
> **For PR 1241**
> 
> ```
> Traceback (most recent call last):
>   File "parallel_model_1241.py", line 176, in <module>
>     model = ParallelModel(model, GPU_COUNT)
>   File "parallel_model_1241.py", line 42, in __init__
>     merged_outputs = self.make_parallel(inner_model)
>   File "parallel_model_1241.py", line 71, in make_parallel
>     for name, x in zip(inner_model.input_names,
> TypeError: 'NoneType' object is not iterable
> ```
> 
> **For PR 1261**
> 
> ```
> Traceback (most recent call last):
>   File "parallel_model.py", line 181, in <module>
>     model = ParallelModel(model, GPU_COUNT)
>   File "parallel_model.py", line 36, in __init__
>     merged_outputs = self.make_parallel(keras_model,gpu_count)
>   File "parallel_model.py", line 90, in make_parallel
>     inputs = [
>   File "parallel_model.py", line 91, in <listcomp>
>     KL.Lambda(lambda s: input_slices[name][i],
>   File "C:\Apps\Anaconda3\envs\FishSeg\lib\site-packages\keras\utils\traceback_utils.py", line 67, in error_handler
>     raise e.with_traceback(filtered_tb) from None
>   File "C:\Apps\Anaconda3\envs\FishSeg\lib\site-packages\tensorflow\python\framework\type_spec.py", line 867, in type_spec_from_value
>     raise TypeError(f"Could not build a TypeSpec for {value} of "
> TypeError: Could not build a TypeSpec for KerasTensor(type_spec=TensorSpec(shape=(None, 28, 28, 1), dtype=tf.float32, name=None), name='tf.split/split:0', description="created by layer 'tf.split'") of unsupported type <class 'keras.engine.keras_tensor.KerasTensor'>.
> ```
> 
> Except for the two PR, I also test another version of `parallel_model.py`, which is claimed to be suitable for keras 2.4.0 (check [here](https://gist.github.com/skywalkerisnull/cebc1fc2b00fa76da92173d2baa21714)). The error message is the same as the current parallel_model.py version. It seems to be related to keras version, but I want to stick to the current keras 2.7.0 in case some other errors occur. Could you take time to see how to revise the `parallel_model.py` to make it suitable for this set of Mask_RCNN? Thanks for your patience and great works!
> 
> Best, Erin

However, your [solution](https://github.com/Kamlesh364/Mask-RCNN-TF2.7.0-keras2.7.0/issues/6#issuecomment-1171234677) is not the correct hammer to problem with the uses of `parallel_model.py`. The issue can only be solved by solving the [quoted ](https://github.com/Kamlesh364/Mask-RCNN-TF2.7.0-keras2.7.0/issues/6#issuecomment-1158910313) issue.
