### ISSUE TITLE
The result of visualize.display_instances is not correct

### ISSUE THREAD

**Issue by XUYIRS** [Kamlesh364/Mask-RCNN-TF2.7.0-keras2.7.0#8]
![image](https://user-images.githubusercontent.com/31101718/174588300-b1127cff-7fd1-4b72-9e5a-20f284ceab8e.png)

**Comment by Kamlesh364** [comment]
@XUYIRS 
Please follow [this](https://github.com/Kamlesh364/Mask-RCNN-TF2.7.0-keras2.7.0/issues/1) conversation.

best regards,
Kamlesh

**Comment by XUYIRS** [comment]
@Kamlesh364 
Thanks a lot. It perfectly solved the problem.

Best,
Yi
